### ISSUE TITLE
Restore app causes RegisterViewModels to crash

### ISSUE THREAD

**Issue by rasmuschristensen** [codemillmatt/codemill.vmfirstnav#13]
Hi,

Not sure what best practics is or if there is a bug. I've added ` NavigationService.Instance.RegisterViewModels(typeof(App).Assembly);` to MainActivity as in the demo project. If I have a page where BackPress is returning false and this was the first page I navigated to PushAsync, then the app is shutdown. When I resore it, the RegisterViewModels call crashed inside MainActivity. Should I do something or is this support to be handle by this lib?

**Comment by rasmuschristensen** [comment]
Maybe 

`public void Register(Type viewModelType, Type viewType)
		{
			_viewModelViewDictionary.Add(viewModelType, viewType);
		}`

Should include a check to see if the vm ws already registered? What is best practics?

**Comment by codemillmatt** [comment]
PR #14 merged
